let car = 'porshe';
console.log("Is car == 'porshe'? I predict True.");
console.log(car == 'porshe');
console.log("Is car == 'BMW'? I predict False.");
console.log(car == 'BMW');
let book = 'hunting adeline';
console.log("Is this'hunting adeline'? i predict true. ");
console.log(book == 'hunting adeline');
console.log("Is this 'twisted love'? i predict false.");
console.log(book == 'twisted love');
let food = 'burger';
console.log("IS this 'burger'? i pridict True.");
console.log(food == 'burger');
console.log("Is this 'pizza'? i pridict false.");
console.log(food == 'pizza');
let bikes = 'yamaha';
console.log("Is this 'yamaha'? i pridict true.");
console.log(bikes == 'yamaha');
console.log("Is this 'honda'? i pridict false. ");
console.log(bikes == 'honda');
let cakes = 'red velvet cake';
console.log("Is this 'red velvet cake'? i pridict true.");
console.log(cakes == 'red velvet cake');
console.log("Is this 'chocolate cake'? i pridict false. ");
console.log(cakes == 'chocolate cake');
export {};
